#-*- coding:utf-8 -*-

document :
    filename : 'errors 3032_revisio'
    sheet : 'Casos per passar SCRIPT'
    potenciaIntervalCells : F2:F46
    idpolissaIntervalCells : A2:A46
    datainiciIntervalCells : D2:D46
    potenciaactivaIntervalCells: E2:E46

